### ISSUE TITLE
Traps

### ISSUE THREAD

**Issue by daryoush12** [Gonzako/weekly182#1]
Add traps and interactable items into game:

- [ ] Wind turbine (Push marble up)
- [ ] Teleporter

**Comment by Unskilledcrab** [comment]
Adding the following

- [ ] BaseInteractable (handles collision detection and adds default event handlers for others to subscribe to)
- [ ] Trap (handles taking away player health)
- [ ] WindTurbine (handles applying force to a player)
- [ ] Teleporter (handles teleporting a player)
